sudo: required

language: python
python:
  - 3.6

install:
  - pip install coveralls

services:
  - docker

before_install:
  - docker build . -t topverbs

script:
  - docker run --rm topverbs make debug
  - docker run --rm topverbs make qa

after_success:
  - coverage run --source=mypkg setup.py test
  - COVERALLS_REPO_TOKEN=aiHkQCR80g7rHVYDwYzuJad0tafh94uUw coveralls