language: python

python:
  - "3.6"
  - "3.7"

services:
  - docker

install:
  - pip install git+https://github.com/mitrofun/topverbs

before_install:
  - docker build . -t topverbs

script:
  # test run script in develop mode
  - docker run --rm topverbs make debug
  # test code with pytest
  - docker run --rm topverbs make qa
  # test install to pip and run command from cli
  - topverbs -d .